# Generated by Django 3.0.7 on 2020-06-28 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('validity_period', models.BooleanField(default=True)),
                ('series', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParsedFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=100, unique=True)),
                ('series', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('event_date', models.DateTimeField()),
                ('date_recorded', models.DateTimeField()),
                ('event_registration_authority', models.CharField(max_length=100)),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.DocumentType')),
            ],
        ),
    ]
