# Generated by Django 3.0.7 on 2020-06-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostdocument',
            name='date_recorded',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lostdocument',
            name='event_date',
            field=models.CharField(max_length=100),
        ),
    ]
